
const countries = {
    "Zimbabwe":{
        capital: "Harare",
        officialName: "Republic of Zimbabwe",
        population: "17073087",
        area: "390757",
        flag: "https://flagcdn.com/w320/zw.png",
        languages: ["Chibarwe","English","Kalanga","Khoisan","Ndau","Northern Ndebele","Chewa","Shona","Sotho","Tonga","Tswana","Tsonga","Venda","Xhosa","Zimbabwean Sign Language"],
        continents: ["Africa"],
    },
    "Kiribati":{
        capital: "South Tarawa",
        officialName: "Independent and Sovereign Republic of Kiribati",
        population: "120740",
        area: "811",
        flag: "https://flagcdn.com/w320/ki.png",
        languages: ["English","Gilbertese"],
        continents: ["Oceania"],
    },
    "Ghana":{
        capital: "Accra",
        officialName: "Republic of Ghana",
        population: "33742380",
        area: "238533",
        flag: "https://flagcdn.com/w320/gh.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "North Korea":{
        capital: "Pyongyang",
        officialName: "Democratic People's Republic of Korea",
        population: "25950000",
        area: "120538",
        flag: "https://flagcdn.com/w320/kp.png",
        languages: ["Korean"],
        continents: ["Asia"],
    },
    "Spain":{
        capital: "Madrid",
        officialName: "Kingdom of Spain",
        population: "49315949",
        area: "505992",
        flag: "https://flagcdn.com/w320/es.png",
        languages: ["Spanish","Catalan","Basque","Galician"],
        continents: ["Europe"],
    },
    "Jordan":{
        capital: "Amman",
        officialName: "Hashemite Kingdom of Jordan",
        population: "11734000",
        area: "89342",
        flag: "https://flagcdn.com/w320/jo.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
        "San Marino":{
        capital: "City of San Marino",
        officialName: "Republic of San Marino",
        population: "34132",
        area: "61",
        flag: "https://flagcdn.com/w320/sm.png",
        languages: ["Italian"],
        continents: ["Europe"],
    },
        "Ivory Coast":{
        capital: "Yamoussoukro",
        officialName: "Republic of Côte d'Ivoire",
        population: "31719275",
        area: "322463",
        flag: "https://flagcdn.com/w320/ci.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Brazil":{
        capital: "Brasília",
        officialName: "Federative Republic of Brazil",
        population: "213421037",
        area: "8515767",
        flag: "https://flagcdn.com/w320/br.png",
        languages: ["Portuguese"],
        continents: ["South America"],
    },
    "Colombia":{
        capital: "Bogotá",
        officialName: "Republic of Colombia",
        population: "53057212",
        area: "1141748",
        flag: "https://flagcdn.com/w320/co.png",
        languages: ["Spanish"],
        continents: ["South America"],
    },
    "Heard Island and McDonald Islands":{
        capital: "",
        officialName: "Heard Island and McDonald Islands",
        population: "0",
        area: "412",
        flag: "https://flagcdn.com/w320/hm.png",
        languages: ["English"],
        continents: ["Antarctica"],
    },
    "Dominica":{
        capital: "Roseau",
        officialName: "Commonwealth of Dominica",
        population: "67408",
        area: "751",
        flag: "https://flagcdn.com/w320/dm.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Djibouti":{
        capital: "Djibouti",
        officialName: "Republic of Djibouti",
        population: "1066809",
        area: "23200",
        flag: "https://flagcdn.com/w320/dj.png",
        languages: ["Arabic","French"],
        continents: ["Africa"],
    },
    "Slovenia":{
        capital: "Ljubljana",
        officialName: "Republic of Slovenia",
        population: "2130638",
        area: "20273",
        flag: "https://flagcdn.com/w320/si.png",
        languages: ["Slovene"],
        continents: ["Europe"],
    },
    "Anguilla":{
        capital: "The Valley",
        officialName: "Anguilla",
        population: "16010",
        area: "91",
        flag: "https://flagcdn.com/w320/ai.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "North Macedonia":{
        capital: "Skopje",
        officialName: "Republic of North Macedonia",
        population: "1822612",
        area: "25713",
        flag: "https://flagcdn.com/w320/mk.png",
        languages: ["Macedonian"],
        continents: ["Europe"],
    },
    "Solomon Islands":{
        capital: "Honiara",
        officialName: "Solomon Islands",
        population: "750325",
        area: "28896",
        flag: "https://flagcdn.com/w320/sb.png",
        languages: ["English"],
        continents: ["Oceania"],
    },
    "Chad":{
        capital: "N'Djamena",
        officialName: "Republic of Chad",
        population: "19340757",
        area: "1284000",
        flag: "https://flagcdn.com/w320/td.png",
        languages: ["Arabic","French"],
        continents: ["Africa"],
    },
    "Burundi":{
        capital: "Gitega",
        officialName: "Republic of Burundi",
        population: "12332788",
        area: "27834",
        flag: "https://flagcdn.com/w320/bi.png",
        languages: ["French","Kirundi"],
        continents: ["Africa"],
    },
    "Italy":{
        capital: "Rome",
        officialName: "Italian Republic",
        population: "58927633",
        area: "301336",
        flag: "https://flagcdn.com/w320/it.png",
        languages: ["Italian","Catalan"],
        continents: ["Europe"],
    },
    "Ethiopia":{
        capital: "Addis Ababa",
        officialName: "Federal Democratic Republic of Ethiopia",
        population: "111652998",
        area: "1104300",
        flag: "https://flagcdn.com/w320/et.png",
        languages: ["Amharic"],
        continents: ["Africa"],
    },
    "Vietnam":{
        capital: "Hanoi",
        officialName: "Socialist Republic of Vietnam",
        population: "101343800",
        area: "331212",
        flag: "https://flagcdn.com/w320/vn.png",
        languages: ["Vietnamese"],
        continents: ["Asia"],
    },
    "Togo":{
        capital: "Lomé",
        officialName: "Togolese Republic",
        population: "8095498",
        area: "56785",
        flag: "https://flagcdn.com/w320/tg.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Martinique":{
        capital: "Fort-de-France",
        officialName: "Martinique",
        population: "349925",
        area: "1128",
        flag: "https://flagcdn.com/w320/mq.png",
        languages: ["French"],
        continents: ["North America"],
    },
    "Poland":{
        capital: "Warsaw",
        officialName: "Republic of Poland",
        population: "37392000",
        area: "312679",
        flag: "https://flagcdn.com/w320/pl.png",
        languages: ["Polish"],
        continents: ["Europe"],
    },
    "Portugal":{
        capital: "Lisbon",
        officialName: "Portuguese Republic",
        population: "10749635",
        area: "92090",
        flag: "https://flagcdn.com/w320/pt.png",
        languages: ["Portuguese"],
        continents: ["Europe"],
    },
    "Christmas Island":{
        capital: "Flying Fish Cove",
        officialName: "Territory of Christmas Island",
        population: "1692",
        area: "135",
        flag: "https://flagcdn.com/w320/cx.png",
        languages: ["English"],
        continents: ["Asia"],
    },
    "Israel":{
        capital: "Jerusalem",
        officialName: "State of Israel",
        population: "10134800",
        area: "21937",
        flag: "https://flagcdn.com/w320/il.png",
        languages: ["Arabic","Hebrew"],
        continents: ["Asia"],
    },
    "Argentina":{
        capital: "Buenos Aires",
        officialName: "Argentine Republic",
        population: "46735004",
        area: "2780400",
        flag: "https://flagcdn.com/w320/ar.png",
        languages: ["Guaraní","Spanish"],
        continents: ["South America"],
    },
    "Afghanistan":{
        capital: "Kabul",
        officialName: "Islamic Republic of Afghanistan",
        population: "43844000",
        area: "652230",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
        languages: ["Dari","Pashto","Turkmen"],
        continents: ["Asia"],
    },
    "Papua New Guinea":{
        capital: "Port Moresby",
        officialName: "Independent State of Papua New Guinea",
        population: "11781559",
        area: "462840",
        flag: "https://flagcdn.com/w320/pg.png",
        languages: ["English","Hiri Motu","Tok Pisin"],
        continents: ["Oceania"],
    },
    "New Zealand":{
        capital: "Wellington",
        officialName: "New Zealand",
        population: "5324700",
        area: "268838",
        flag: "https://flagcdn.com/w320/nz.png",
        languages: ["English","Māori","New Zealand Sign Language"],
        continents: ["Oceania"],
    },
    "El Salvador":{
        capital: "San Salvador",
        officialName: "Republic of El Salvador",
        population: "6029976",
        area: "21041",
        flag: "https://flagcdn.com/w320/sv.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Czechia":{
        capital: "Prague",
        officialName: "Czech Republic",
        population: "10882341",
        area: "78865",
        flag: "https://flagcdn.com/w320/cz.png",
        languages: ["Czech","Slovak"],
        continents: ["Europe"],
    },
    "Cameroon":{
        capital: "Yaoundé",
        officialName: "Republic of Cameroon",
        population: "29442327",
        area: "475442",
        flag: "https://flagcdn.com/w320/cm.png",
        languages: ["English","French"],
        continents: ["Africa"],
    },
    "Yemen":{
        capital: "Sana'a",
        officialName: "Republic of Yemen",
        population: "32684503",
        area: "527968",
        flag: "https://flagcdn.com/w320/ye.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "Panama":{
        capital: "Panama City",
        officialName: "Republic of Panama",
        population: "4064780",
        area: "75417",
        flag: "https://flagcdn.com/w320/pa.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Timor-Leste":{
        capital: "Dili",
        officialName: "Democratic Republic of Timor-Leste",
        population: "1391221",
        area: "14874",
        flag: "https://flagcdn.com/w320/tl.png",
        languages: ["Portuguese","Tetum"],
        continents: ["Oceania"],
    },
    "Cuba":{
        capital: "Havana",
        officialName: "Republic of Cuba",
        population: "9748007",
        area: "109884",
        flag: "https://flagcdn.com/w320/cu.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Russia":{
        capital: "Moscow",
        officialName: "Russian Federation",
        population: "146028325",
        area: "17098246",
        flag: "https://flagcdn.com/w320/ru.png",
        languages: ["Russian"],
        continents: ["Europe","Asia"],
    },
    "Antigua and Barbuda":{
        capital: "Saint John's",
        officialName: "Antigua and Barbuda",
        population: "103603",
        area: "442",
        flag: "https://flagcdn.com/w320/ag.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Saint Barthélemy":{
        capital: "Gustavia",
        officialName: "Collectivity of Saint Barthélemy",
        population: "10562",
        area: "21",
        flag: "https://flagcdn.com/w320/bl.png",
        languages: ["French"],
        continents: ["North America"],
    },
    "Bolivia":{
        capital: "Sucre",
        officialName: "Plurinational State of Bolivia",
        population: "11365333",
        area: "1098581",
        flag: "https://flagcdn.com/w320/bo.png",
        languages: ["Aymara","Guaraní","Quechua","Spanish"],
        continents: ["South America"],
    },
    "Australia":{
        capital: "Canberra",
        officialName: "Commonwealth of Australia",
        population: "27536874",
        area: "7692024",
        flag: "https://flagcdn.com/w320/au.png",
        languages: ["English"],
        continents: ["Oceania"],
    },
    "United States Minor Outlying Islands":{
    capital: "Washington DC",
        officialName: "United States Minor Outlying Islands",
        population: "0",
        area: "34.2",
        flag: "https://flagcdn.com/w320/um.png",
        languages: ["English"],
        continents: ["Oceania"],
    },
    "Fiji":{
        capital: "Suva",
        officialName: "Republic of Fiji",
        population: "900869",
        area: "18272",
        flag: "https://flagcdn.com/w320/fj.png",
        languages: ["English","Fijian","Fiji Hindi"],
        continents: ["Oceania"],
    },
    "Myanmar":{
        capital: "Naypyidaw",
        officialName: "Republic of the Union of Myanmar",
        population: "51316756",
        area: "676578",
        flag: "https://flagcdn.com/w320/mm.png",
        languages: ["Burmese"],
        continents: ["Asia"],
    },
    "São Tomé and Príncipe":{
        capital: "São Tomé",
        officialName: "Democratic Republic of São Tomé and Príncipe",
        population: "209607",
        area: "964",
        flag: "https://flagcdn.com/w320/st.png",
        languages: ["Portuguese"],
        continents: ["Africa"],
    },
    "Madagascar":{
        capital: "Antananarivo",
        officialName: "Republic of Madagascar",
        population: "31727042",
        area: "587041",
        flag: "https://flagcdn.com/w320/mg.png",
        languages: ["French","Malagasy"],
        continents: ["Africa"],
    },
    "Tuvalu":{
        capital: "Funafuti",
        officialName: "Tuvalu",
        population: "10643",
        area: "26",
        flag: "https://flagcdn.com/w320/tv.png",
        languages: ["English","Tuvaluan"],
        continents: ["Oceania"],
    },
    "Guernsey":{
        capital: "St. Peter Port",
        officialName: "Bailiwick of Guernsey",
        population: "64781",
        area: "78",
        flag: "https://flagcdn.com/w320/gg.png",
        languages: ["English","French","Guernésiais"],
        continents: ["Europe"],
    },
    "Cocos (Keeling) Islands":{
        capital: "West Island",
        officialName: "Territory of the Cocos (Keeling) Islands",
        population: "593",
        area: "14",
        flag: "https://flagcdn.com/w320/cc.png",
        languages: ["English"],
        continents: ["Asia"],
    },
    "Hungary":{
        capital: "Budapest",
        officialName: "Hungary",
        population: "9539502",
        area: "93028",
        flag: "https://flagcdn.com/w320/hu.png",
        languages: ["Hungarian"],
        continents: ["Europe"],
    },
    "Egypt":{
        capital: "Cairo",
        officialName: "Arab Republic of Egypt",
        population: "107271260",
        area: "1002450",
        flag: "https://flagcdn.com/w320/eg.png",
        languages: ["Arabic"],
        continents: ["Africa"],
    },
    "Kyrgyzstan":{
        capital: "Bishkek",
        officialName: "Kyrgyz Republic",
        population: "7281800",
        area: "199951",
        flag: "https://flagcdn.com/w320/kg.png",
        languages: ["Kyrgyz","Russian"],
        continents: ["Asia"],
    },
    "Indonesia":{
        capital: "Jakarta",
        officialName: "Republic of Indonesia",
        population: "284438782",
        area: "1904569",
        flag: "https://flagcdn.com/w320/id.png",
        languages: ["Indonesian"],
        continents: ["Asia"],
    },
    "Tunisia":{
        capital: "Tunis",
        officialName: "Tunisian Republic",
        population: "11972169",
        area: "163610",
        flag: "https://flagcdn.com/w320/tn.png",
        languages: ["Arabic"],
        continents: ["Africa"],
    },
    "American Samoa":{
        capital: "Pago Pago",
        officialName: "American Samoa",
        population: "49710",
        area: "199",
        flag: "https://flagcdn.com/w320/as.png",
        languages: ["English","Samoan"],
        continents: ["Oceania"],
    },
    "Oman":{
        capital: "Muscat",
        officialName: "Sultanate of Oman",
        population: "5343630",
        area: "309500",
        flag: "https://flagcdn.com/w320/om.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "French Polynesia":{
        capital: "Papeetē",
        officialName: "French Polynesia",
        population: "279500",
        area: "4167",
        flag: "https://flagcdn.com/w320/pf.png",
        languages: ["French"],
        continents: ["Oceania"],
    },
    "United States":{
        capital: "Washington, D.C.",
        officialName: "United States of America",
        population: "340110988",
        area: "9525067",
        flag: "https://flagcdn.com/w320/us.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Falkland Islands":{
        capital: "Stanley",
        officialName: "Falkland Islands",
        population: "3662",
        area: "12173",
        flag: "https://flagcdn.com/w320/fk.png",
        languages: ["English"],
        continents: ["South America"],
    },
    "Saint Martin":{
        capital: "Marigot",
        officialName: "Saint Martin",
        population: "31496",
        area: "53",
        flag: "https://flagcdn.com/w320/mf.png",
        languages: ["French"],
        continents: ["North America"],
    },
    "Suriname":{
        capital: "Paramaribo",
        officialName: "Republic of Suriname",
        population: "616500",
        area: "163820",
        flag: "https://flagcdn.com/w320/sr.png",
        languages: ["Dutch"],
        continents: ["South America"],
    },
    "Azerbaijan":{
        capital: "Baku",
        officialName: "Republic of Azerbaijan",
        population: "10241722",
        area: "86600",
        flag: "https://flagcdn.com/w320/az.png",
        languages: ["Azerbaijani"],
        continents: ["Europe","Asia"],
    },
    "Netherlands":{
        capital: "Amsterdam",
        officialName: "Kingdom of the Netherlands",
        population: "18100436",
        area: "41865",
        flag: "https://flagcdn.com/w320/nl.png",
        languages: ["Dutch"],
        continents: ["Europe"],
    },
    "Palestine":{
        capital: "Ramallah",
        officialName: "State of Palestine",
        population: "5483450",
        area: "6220",
        flag: "https://flagcdn.com/w320/ps.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "Slovakia":{
        capital: "Bratislava",
        officialName: "Slovak Republic",
        population: "5413813",
        area: "49037",
        flag: "https://flagcdn.com/w320/sk.png",
        languages: ["Slovak"],
        continents: ["Europe"],
    },
    "Uganda":{
        capital: "Kampala",
        officialName: "Republic of Uganda",
        population: "45905417",
        area: "241550",
        flag: "https://flagcdn.com/w320/ug.png",
        languages: ["English","Swahili"],
        continents: ["Africa"],
    },
    "Cayman Islands":{
        capital: "George Town",
        officialName: "Cayman Islands",
        population: "84738",
        area: "264",
        flag: "https://flagcdn.com/w320/ky.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Saint Lucia":{
        capital: "Castries",
        officialName: "Saint Lucia",
        population: "184100",
        area: "616",
        flag: "https://flagcdn.com/w320/lc.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Libya":{
        capital: "Tripoli",
        officialName: "State of Libya",
        population: "7459000",
        area: "1759540",
        flag: "https://flagcdn.com/w320/ly.png",
        languages: ["Arabic"],
        continents: ["Africa"],
    },
    "Northern Mariana Islands":{
        capital: "Saipan",
        officialName: "Commonwealth of the Northern Mariana Islands",
        population: "47329",
        area: "464",
        flag: "https://flagcdn.com/w320/mp.png",
        languages: ["Carolinian","Chamorro","English"],
        continents: ["Oceania"],
    },
    "Armenia":{
        capital: "Yerevan",
        officialName: "Republic of Armenia",
        population: "3076200",
        area: "29743",
        flag: "https://flagcdn.com/w320/am.png",
        languages: ["Armenian"],
        continents: ["Asia"],
    },
    "Comoros":{
        capital: "Moroni",
        officialName: "Union of the Comoros",
        population: "919901",
        area: "1862",
        flag: "https://flagcdn.com/w320/km.png",
        languages: ["Arabic","French","Comorian"],
        continents: ["Africa"],
        },
    "Guyana":{
        capital: "Georgetown",
        officialName: "Co-operative Republic of Guyana",
        population: "772975",
        area: "214969",
        flag: "https://flagcdn.com/w320/gy.png",
        languages: ["English"],
        continents: ["South America"],
    },
    "United Arab Emirates":{
        capital: "Abu Dhabi",
        officialName: "United Arab Emirates",
        population: "11294243",
        area: "83600",
        flag: "https://flagcdn.com/w320/ae.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "Turkey":{
        capital: "Ankara",
        officialName: "Republic of Turkey",
        population: "85664944",
        area: "783562",
        flag: "https://flagcdn.com/w320/tr.png",
        languages: ["Turkish"],
        continents: ["Europe","Asia"],
    },
    "Samoa":{
        capital: "Apia",
        officialName: "Independent State of Samoa",
        population: "205557",
        area: "2842",
        flag: "https://flagcdn.com/w320/ws.png",
        languages: ["English","Samoan"],
        continents: ["Oceania"],
    },
    "Germany":{
        capital: "Berlin",
        officialName: "Federal Republic of Germany",
        population: "83491249",
        area: "357114",
        flag: "https://flagcdn.com/w320/de.png",
        languages: ["German"],
        continents: ["Europe"],
    },
    "Gambia":{
        capital: "Banjul",
        officialName: "Republic of the Gambia",
        population: "2422712",
        area: "10689",
        flag: "https://flagcdn.com/w320/gm.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "Mongolia":{
        capital: "Ulan Bator",
        officialName: "Mongolia",
        population: "3544835",
        area: "1564110",
        flag: "https://flagcdn.com/w320/mn.png",
        languages: ["Mongolian"],
        continents: ["Asia"],
    },
    "Serbia":{
        capital: "Belgrade",
        officialName: "Republic of Serbia",
        population: "6567783",
        area: "77589",
        flag: "https://flagcdn.com/w320/rs.png",
        languages: ["Serbian"],
        continents: ["Europe"],
    },
    "China":{
        capital: "Beijing",
        officialName: "People's Republic of China",
        population: "1408280000",
        area: "9706961",
        flag: "https://flagcdn.com/w320/cn.png",
        languages: ["Chinese"],
        continents: ["Asia"],
    },
    "Montenegro":{
        capital: "Podgorica",
        officialName: "Montenegro",
        population: "623327",
        area: "13812",
        flag: "https://flagcdn.com/w320/me.png",
        languages: ["Montenegrin"],
        continents: ["Europe"],
    },
    "Guam":{
        capital: "Hagåtña",
        officialName: "Guam",
        population: "153836",
        area: "549",
        flag: "https://flagcdn.com/w320/gu.png",
        languages: ["Chamorro","English","Spanish"],
        continents: ["Oceania"],
    },
    "Cambodia":{
        capital: "Phnom Penh",
        officialName: "Kingdom of Cambodia",
        population: "17577760",
        area: "181035",
        flag: "https://flagcdn.com/w320/kh.png",
        languages: ["Khmer"],
        continents: ["Asia"],
    },
    "Liechtenstein":{
        capital: "Vaduz",
        officialName: "Principality of Liechtenstein",
        population: "40900",
        area: "160",
        flag: "https://flagcdn.com/w320/li.png",
        languages: ["German"],
        continents: ["Europe"],
    },
    "Senegal":{
        capital: "Dakar",
        officialName: "Republic of Senegal",
        population: "18593258",
        area: "196722",
        flag: "https://flagcdn.com/w320/sn.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "United Kingdom":{
        capital: "London",
        officialName: "United Kingdom of Great Britain and Northern Ireland",
        population: "69281437",
        area: "244376",
        flag: "https://flagcdn.com/w320/gb.png",
        languages: ["English"],
        continents: ["Europe"],
    },
    "Caribbean Netherlands":{
        capital: "Kralendijk",
        officialName: "Bonaire, Sint Eustatius and Saba",
        population: "31980",
        area: "328",
        flag: "https://flagcdn.com/w320/bq.png",
        languages: ["English","Dutch","Papiamento"],
        continents: ["North America"],
    },
    "French Guiana":{
        capital: "Cayenne",
        officialName: "Guiana",
        population: "292354",
        area: "83534",
        flag: "https://flagcdn.com/w320/gf.png",
        languages: ["French"],
        continents: ["South America"],
    },
    "Burkina Faso":{
        capital: "Ouagadougou",
        officialName: "Burkina Faso",
        population: "24070553",
        area: "272967",
        flag: "https://flagcdn.com/w320/bf.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Qatar":{
        capital: "Doha",
        officialName: "State of Qatar",
        population: "3173024",
        area: "11586",
        flag: "https://flagcdn.com/w320/qa.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "Ukraine":{
        capital: "Kyiv",
        officialName: "Ukraine",
        population: "32862000",
        area: "603550",
        flag: "https://flagcdn.com/w320/ua.png",
        languages: ["Ukrainian"],
        continents: ["Europe"],
    },
    "Mexico":{
        capital: "Mexico City",
        officialName: "United Mexican States",
        population: "130575786",
        area: "1964375",
        flag: "https://flagcdn.com/w320/mx.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Isle of Man":{
        capital: "Douglas",
        officialName: "Isle of Man",
        population: "84530",
        area: "572",
        flag: "https://flagcdn.com/w320/im.png",
        languages: ["English","Manx"],
        continents: ["Europe"],
        },
    "Antarctica":{
        capital: "",
        officialName: "Antarctica",
        population: "1300",
        area: "14000000",
        flag: "https://flagcdn.com/w320/aq.png",
        languages: [],
        continents: ["Antarctica"],
    },
    "South Georgia":{
        capital: "King Edward Point",
        officialName: "South Georgia and the South Sandwich Islands",
        population: "0",
        area: "3903",
        flag: "https://flagcdn.com/w320/gs.png",
        languages: ["English"],
        continents: ["Antarctica"],
    },
    "Western Sahara":{
        capital: "El Aaiún",
        officialName: "Sahrawi Arab Democratic Republic",
        population: "600904",
        area: "266000",
        flag: "https://flagcdn.com/w320/eh.png",
        languages: ["Berber","Hassaniya","Spanish"],
        continents: ["Africa"],
    },
    "Turks and Caicos Islands":{
        capital: "Cockburn Town",
        officialName: "Turks and Caicos Islands",
        population: "50828",
        area: "948",
        flag: "https://flagcdn.com/w320/tc.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Albania":{
        capital: "Tirana",
        officialName: "Republic of Albania",
        population: "2363314",
        area: "28748",
        flag: "https://flagcdn.com/w320/al.png",
        languages: ["Albanian"],
        continents: ["Europe"],
    },
    "Cyprus":{
        capital: "Nicosia",
        officialName: "Republic of Cyprus",
        population: "1442614",
        area: "9251",
        flag: "https://flagcdn.com/w320/cy.png",
        languages: ["Greek","Turkish"],
        continents: ["Europe"],
    },
    "Guatemala":{
        capital: "Guatemala City",
        officialName: "Republic of Guatemala",
        population: "18079810",
        area: "108889",
        flag: "https://flagcdn.com/w320/gt.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Nauru":{
        capital: "Yaren",
        officialName: "Republic of Nauru",
        population: "11680",
        area: "21",
        flag: "https://flagcdn.com/w320/nr.png",
        languages: ["English","Nauru"],
        continents: ["Oceania"],
    },
    "Saint Helena, Ascension and Tristan da Cunha":{
        capital: "Jamestown",
        officialName: "Saint Helena, Ascension and Tristan da Cunha",
        population: "5651",
        area: "394",
        flag: "https://flagcdn.com/w320/sh.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "Latvia":{
        capital: "Riga",
        officialName: "Republic of Latvia",
        population: "1829000",
        area: "64559",
        flag: "https://flagcdn.com/w320/lv.png",
        languages: ["Latvian"],
        continents: ["Europe"],
    },
    "Cook Islands":{
        capital: "Avarua",
        officialName: "Cook Islands",
        population: "15040",
        area: "236",
        flag: "https://flagcdn.com/w320/ck.png",
        languages: ["English","Cook Islands Māori"],
        continents: ["Oceania"],
    },
    "Malta":{
        capital: "Valletta",
        officialName: "Republic of Malta",
        population: "574250",
        area: "316",
        flag: "https://flagcdn.com/w320/mt.png",
        languages: ["English","Maltese"],
        continents: ["Europe"],
    },
    "Pitcairn Islands":{
        capital: "Adamstown",
        officialName: "Pitcairn Group of Islands",
        population: "35",
        area: "47",
        flag: "https://flagcdn.com/w320/pn.png",
        languages: ["English"],
        continents: ["Oceania"],
    },
    "South Korea":{
        capital: "Seoul",
        officialName: "Republic of Korea",
        population: "51159889",
        area: "100210",
        flag: "https://flagcdn.com/w320/kr.png",
        languages: ["Korean"],
        continents: ["Asia"],
    },
    "New Caledonia":{
        capital: "Nouméa",
        officialName: "New Caledonia",
        population: "264596",
        area: "18575",
        flag: "https://flagcdn.com/w320/nc.png",
        languages: ["French"],
        continents: ["Oceania"],
    },
    "Mozambique":{
        capital: "Maputo",
        officialName: "Republic of Mozambique",
        population: "34090466",
        area: "801590",
        flag: "https://flagcdn.com/w320/mz.png",
        languages: ["Portuguese"],
        continents: ["Africa"],
    },
    "Luxembourg":{
        capital: "Luxembourg",
        officialName: "Grand Duchy of Luxembourg",
        population: "681973",
        area: "2586",
        flag: "https://flagcdn.com/w320/lu.png",
        languages: ["German","French","Luxembourgish"],
        continents: ["Europe"],
    },
    "Ireland":{
        capital: "Dublin",
        officialName: "Republic of Ireland",
        population: "5458600",
        area: "70273",
        flag: "https://flagcdn.com/w320/ie.png",
        languages: ["English","Irish"],
        continents: ["Europe"],
    },
    "Nigeria":{
        capital: "Abuja",
        officialName: "Federal Republic of Nigeria",
        population: "223800000",
        area: "923768",
        flag: "https://flagcdn.com/w320/ng.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "Bahamas":{
        capital: "Nassau",
        officialName: "Commonwealth of the Bahamas",
        population: "398165",
        area: "13943",
        flag: "https://flagcdn.com/w320/bs.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Marshall Islands":{
        capital: "Majuro",
        officialName: "Republic of the Marshall Islands",
        population: "42418",
        area: "181",
        flag: "https://flagcdn.com/w320/mh.png",
        languages: ["English","Marshallese"],
        continents: ["Oceania"],
    },
    "Greece":{
        capital: "Athens",
        officialName: "Hellenic Republic",
        population: "10400720",
        area: "131990",
        flag: "https://flagcdn.com/w320/gr.png",
        languages: ["Greek"],
        continents: ["Europe"],
    },
    "Maldives":{
        capital: "Malé",
        officialName: "Republic of the Maldives",
        population: "515132",
        area: "300",
        flag: "https://flagcdn.com/w320/mv.png",
        languages: ["Maldivian"],
        continents: ["Asia"],
    },
    "Niue":{
        capital: "Alofi",
        officialName: "Niue",
        population: "1681",
        area: "260",
        flag: "https://flagcdn.com/w320/nu.png",
        languages: ["English","Niuean"],
        continents: ["Oceania"],
    },
    "Syria":{
        capital: "Damascus",
        officialName: "Syrian Arab Republic",
        population: "25620000",
        area: "185180",
        flag: "https://flagcdn.com/w320/sy.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "Ecuador":{
        capital: "Quito",
        officialName: "Republic of Ecuador",
        population: "18103660",
        area: "276841",
        flag: "https://flagcdn.com/w320/ec.png",
        languages: ["Spanish"],
        continents: ["South America"],
    },
    "Turkmenistan":{
        capital: "Ashgabat",
        officialName: "Turkmenistan",
        population: "7057841",
        area: "488100",
        flag: "https://flagcdn.com/w320/tm.png",
        languages: ["Russian","Turkmen"],
        continents: ["Asia"],
    },
    "Wallis and Futuna":{
        capital: "Mata-Utu",
        officialName: "Territory of the Wallis and Futuna Islands",
        population: "11620",
        area: "142",
        flag: "https://flagcdn.com/w320/wf.png",
        languages: ["French"],
        continents: ["Oceania"],
    },
    "Brunei":{
        capital: "Bandar Seri Begawan",
        officialName: "Nation of Brunei, Abode of Peace",
        population: "455500",
        area: "5765",
        flag: "https://flagcdn.com/w320/bn.png",
        languages: ["Malay"],
        continents: ["Asia"],
    },
    "Uzbekistan":{
        capital: "Tashkent",
        officialName: "Republic of Uzbekistan",
        population: "37859698",
        area: "447400",
        flag: "https://flagcdn.com/w320/uz.png",
        languages: ["Russian","Uzbek"],
        continents: ["Asia"],
    },
    "Bahrain":{
        capital: "Manama",
        officialName: "Kingdom of Bahrain",
        population: "1594654",
        area: "765",
        flag: "https://flagcdn.com/w320/bh.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "British Virgin Islands":{
        capital: "Road Town",
        officialName: "Virgin Islands",
        population: "39471",
        area: "151",
        flag: "https://flagcdn.com/w320/vg.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Moldova":{
        capital: "Chișinău",
        officialName: "Republic of Moldova",
        population: "2749076",
        area: "33847",
        flag: "https://flagcdn.com/w320/md.png",
        languages: ["Romanian"],
        continents: ["Europe"],
    },
    "Mauritius":{
        capital: "Port Louis",
        officialName: "Republic of Mauritius",
        population: "1243741",
        area: "2040",
        flag: "https://flagcdn.com/w320/mu.png",
        languages: ["English","French","Mauritian Creole"],
        continents: ["Africa"],
    },
    "Tonga":{
        capital: "Nuku'alofa",
        officialName: "Kingdom of Tonga",
        population: "100179",
        area: "747",
        flag: "https://flagcdn.com/w320/to.png",
        languages: ["English","Tongan"],
        continents: ["Oceania"],
    },
    "Seychelles":{
        capital: "Victoria",
        officialName: "Republic of Seychelles",
        population: "122729",
        area: "452",
        flag: "https://flagcdn.com/w320/sc.png",
        languages: ["Seychellois Creole","English","French"],
        continents: ["Africa"],
    },
    "Angola":{
        capital: "Luanda",
        officialName: "Republic of Angola",
        population: "36170961",
        area: "1246700",
        flag: "https://flagcdn.com/w320/ao.png",
        languages: ["Portuguese"],
        continents: ["Africa"],
    },
    "Estonia":{
        capital: "Tallinn",
        officialName: "Republic of Estonia",
        population: "1369995",
        area: "45227",
        flag: "https://flagcdn.com/w320/ee.png",
        languages: ["Estonian"],
        continents: ["Europe"],
    },
    "Bermuda":{
        capital: "Hamilton",
        officialName: "Bermuda",
        population: "64055",
        area: "54",
        flag: "https://flagcdn.com/w320/bm.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Philippines":{
        capital: "Manila",
        officialName: "Republic of the Philippines",
        population: "114123600",
        area: "342353",
        flag: "https://flagcdn.com/w320/ph.png",
        languages: ["English","Filipino"],
        continents: ["Asia"],
    },
    "Vatican City":{
        capital: "Vatican City",
        officialName: "Vatican City State",
        population: "882",
        area: "0.49",
        flag: "https://flagcdn.com/w320/va.png",
        languages: ["Italian","Latin"],
        continents: ["Europe"],
    },
    "Venezuela":{
        capital: "Caracas",
        officialName: "Bolivarian Republic of Venezuela",
        population: "28517000",
        area: "916445",
        flag: "https://flagcdn.com/w320/ve.png",
        languages: ["Spanish"],
        continents: ["South America"],
    },
    "Barbados":{
        capital: "Bridgetown",
        officialName: "Barbados",
        population: "267800",
        area: "430",
        flag: "https://flagcdn.com/w320/bb.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "India":{
        capital: "New Delhi",
        officialName: "Republic of India",
        population: "1417492000",
        area: "3287263",
        flag: "https://flagcdn.com/w320/in.png",
        languages: ["English","Hindi","Tamil"],
        continents: ["Asia"],
    },
    "Mali":{
        capital: "Bamako",
        officialName: "Republic of Mali",
        population: "22395489",
        area: "1240192",
        flag: "https://flagcdn.com/w320/ml.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Norfolk Island":{
        capital: "Kingston",
        officialName: "Territory of Norfolk Island",
        population: "2188",
        area: "36",
        flag: "https://flagcdn.com/w320/nf.png",
        languages: ["English","Norfuk"],
        continents: ["Oceania"],
    },
    "Belarus":{
        capital: "Minsk",
        officialName: "Republic of Belarus",
        population: "9109280",
        area: "207600",
        flag: "https://flagcdn.com/w320/by.png",
        languages: ["Belarusian","Russian"],
        continents: ["Europe"],
    },
    "Saint Kitts and Nevis":{
        capital: "Basseterre",
        officialName: "Federation of Saint Christopher and Nevis",
        population: "51320",
        area: "261",
        flag: "https://flagcdn.com/w320/kn.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Guadeloupe":{
        capital: "Basse-Terre",
        officialName: "Guadeloupe",
        population: "378561",
        area: "1628",
        flag: "https://flagcdn.com/w320/gp.png",
        languages: ["French"],
        continents: ["North America"],
    },
    "Lithuania":{
        capital: "Vilnius",
        officialName: "Republic of Lithuania",
        population: "2894886",
        area: "65300",
        flag: "https://flagcdn.com/w320/lt.png",
        languages: ["Lithuanian"],
        continents: ["Europe"],
    },
    "Montserrat":{
        capital: "Plymouth",
        officialName: "Montserrat",
        population: "4386",
        area: "102",
        flag: "https://flagcdn.com/w320/ms.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Niger":{
        capital: "Niamey",
        officialName: "Republic of Niger",
        population: "26312034",
        area: "1267000",
        flag: "https://flagcdn.com/w320/ne.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Equatorial Guinea":{
        capital: "Ciudad de la Paz",
        officialName: "Republic of Equatorial Guinea",
        population: "1668768",
        area: "28051",
        flag: "https://flagcdn.com/w320/gq.png",
        languages: ["French","Portuguese","Spanish"],
        continents: ["Africa"],
    },
    "Iraq":{
        capital: "Baghdad",
        officialName: "Republic of Iraq",
        population: "46118793",
        area: "438317",
        flag: "https://flagcdn.com/w320/iq.png",
        languages: ["Arabic","Aramaic","Sorani"],
        continents: ["Asia"],
    },
    "Mauritania":{
        capital: "Nouakchott",
        officialName: "Islamic Republic of Mauritania",
        population: "4927532",
        area: "1030700",
        flag: "https://flagcdn.com/w320/mr.png",
        languages: ["Arabic"],
        continents: ["Africa"],
    },
    "Taiwan":{
        capital: "Taipei",
        officialName: "Republic of China (Taiwan)",
        population: "23317031",
        area: "36197",
        flag: "https://flagcdn.com/w320/tw.png",
        languages: ["Chinese"],
        continents: ["Asia"],
    },
    "Georgia":{
        capital: "Tbilisi",
        officialName: "Georgia",
        population: "4000921",
        area: "69700",
        flag: "https://flagcdn.com/w320/ge.png",
        languages: ["Georgian"],
        continents: ["Asia"],
    },
    "Puerto Rico":{
        capital: "San Juan",
        officialName: "Commonwealth of Puerto Rico",
        population: "3203295",
        area: "8870",
        flag: "https://flagcdn.com/w320/pr.png",
        languages: ["English","Spanish"],
        continents: ["North America"],
    },
    "Paraguay":{
        capital: "Asunción",
        officialName: "Republic of Paraguay",
        population: "6109644",
        area: "406752",
        flag: "https://flagcdn.com/w320/py.png",
        languages: ["Guaraní","Spanish"],
        continents: ["South America"],
    },
    "Sierra Leone":{
        capital: "Freetown",
        officialName: "Republic of Sierra Leone",
        population: "9077691",
        area: "71740",
        flag: "https://flagcdn.com/w320/sl.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "Botswana":{
        capital: "Gaborone",
        officialName: "Republic of Botswana",
        population: "2359609",
        area: "582000",
        flag: "https://flagcdn.com/w320/bw.png",
        languages: ["English","Tswana"],
        continents: ["Africa"],
    },
    "Mayotte":{
        capital: "Mamoudzou",
        officialName: "Department of Mayotte",
        population: "320901",
        area: "374",
        flag: "https://flagcdn.com/w320/yt.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Finland":{
        capital: "Helsinki",
        officialName: "Republic of Finland",
        population: "5650325",
        area: "338455",
        flag: "https://flagcdn.com/w320/fi.png",
        languages: ["Finnish","Swedish"],
        continents: ["Europe"],
    },
    "Jersey":{
        capital: "Saint Helier",
        officialName: "Bailiwick of Jersey",
        population: "103267",
        area: "116",
        flag: "https://flagcdn.com/w320/je.png",
        languages: ["English","French","Jèrriais"],
        continents: ["Europe"],
    },
    "Faroe Islands":{
        capital: "Tórshavn",
        officialName: "Faroe Islands",
        population: "54885",
        area: "1393",
        flag: "https://flagcdn.com/w320/fo.png",
        languages: ["Danish","Faroese"],
        continents: ["Europe"],
    },
    "Sweden":{
        capital: "Stockholm",
        officialName: "Kingdom of Sweden",
        population: "10605098",
        area: "450295",
        flag: "https://flagcdn.com/w320/se.png",
        languages: ["Swedish"],
        continents: ["Europe"],
    },
    "Sri Lanka":{
        capital: "Sri Jayawardenepura Kotte",
        officialName: "Democratic Socialist Republic of Sri Lanka",
        population: "21763170",
        area: "65610",
        flag: "https://flagcdn.com/w320/lk.png",
        languages: ["Sinhala","Tamil"],
        continents: ["Asia"],
    },
    "Thailand":{
        capital: "Bangkok",
        officialName: "Kingdom of Thailand",
        population: "65859640",
        area: "513120",
        flag: "https://flagcdn.com/w320/th.png",
        languages: ["Thai"],
        continents: ["Asia"],
    },
    "Greenland":{
        capital: "Nuuk",
        officialName: "Greenland",
        population: "56542",
        area: "2166086",
        flag: "https://flagcdn.com/w320/gl.png",
        languages: ["Greenlandic"],
        continents: ["North America"],
    },
    "Bulgaria":{
        capital: "Sofia",
        officialName: "Republic of Bulgaria",
        population: "6437360",
        area: "110879",
        flag: "https://flagcdn.com/w320/bg.png",
        languages: ["Bulgarian"],
        continents: ["Europe"],
    },
    "Kenya":{
        capital: "Nairobi",
        officialName: "Republic of Kenya",
        population: "53330978",
        area: "580367",
        flag: "https://flagcdn.com/w320/ke.png",
        languages: ["English","Swahili"],
        continents: ["Africa"],
    },
    "Hong Kong":{
        capital: "City of Victoria",
        officialName: "Hong Kong Special Administrative Region of the People's Republic of China",
        population: "7527500",
        area: "1104",
        flag: "https://flagcdn.com/w320/hk.png",
        languages: ["English","Chinese"],
        continents: ["Asia"],
    },
    "Romania":{
        capital: "Bucharest",
        officialName: "Romania",
        population: "19036031",
        area: "238391",
        flag: "https://flagcdn.com/w320/ro.png",
        languages: ["Romanian"],
        continents: ["Europe"],
    },
    "Malawi":{
        capital: "Lilongwe",
        officialName: "Republic of Malawi",
        population: "20734262",
        area: "118484",
        flag: "https://flagcdn.com/w320/mw.png",
        languages: ["English","Chewa"],
        continents: ["Africa"],
    },
    "Republic of the Congo":{
        capital: "Brazzaville",
        officialName: "Republic of the Congo",
        population: "6142180",
        area: "342000",
        flag: "https://flagcdn.com/w320/cg.png",
        languages: ["French","Kikongo","Lingala"],
        continents: ["Africa"],
    },
    "Honduras":{
        capital: "Tegucigalpa",
        officialName: "Republic of Honduras",
        population: "9892632",
        area: "112492",
        flag: "https://flagcdn.com/w320/hn.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Aruba":{
        capital: "Oranjestad",
        officialName: "Aruba",
        population: "107566",
        area: "180",
        flag: "https://flagcdn.com/w320/aw.png",
        languages: ["Dutch","Papiamento"],
        continents: ["North America"],
    },
    "Monaco":{
        capital: "Monaco",
        officialName: "Principality of Monaco",
        population: "38423",
        area: "2.02",
        flag: "https://flagcdn.com/w320/mc.png",
        languages: ["French"],
        continents: ["Europe"],
    },
    "Bouvet Island":{
        capital: "",
        officialName: "Bouvet Island",
        population: "0",
        area: "49",
        flag: "https://flagcdn.com/w320/bv.png",
        languages: ["Norwegian"],
        continents: ["Antarctica"],
    },
    "Zambia":{
        capital: "Lusaka",
        officialName: "Republic of Zambia",
        population: "19693423",
        area: "752612",
        flag: "https://flagcdn.com/w320/zm.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "Andorra":{
        capital: "Andorra la Vella",
        officialName: "Principality of Andorra",
        population: "88406",
        area: "468",
        flag: "https://flagcdn.com/w320/ad.png",
        languages: ["Catalan"],
        continents: ["Europe"],
    },
    "Liberia":{
        capital: "Monrovia",
        officialName: "Republic of Liberia",
        population: "5248621",
        area: "111369",
        flag: "https://flagcdn.com/w320/lr.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "Tanzania":{
        capital: "Dodoma",
        officialName: "United Republic of Tanzania",
        population: "68153004",
        area: "947303",
        flag: "https://flagcdn.com/w320/tz.png",
        languages: ["English","Swahili"],
        continents: ["Africa"],
    },
    "Saint Pierre and Miquelon":{
        capital: "Saint-Pierre",
        officialName: "Saint Pierre and Miquelon",
        population: "5819",
        area: "242",
        flag: "https://flagcdn.com/w320/pm.png",
        languages: ["French"],
        continents: ["North America"],
    },
    "Iran":{
        capital: "Tehran",
        officialName: "Islamic Republic of Iran",
        population: "85961000",
        area: "1648195",
        flag: "https://flagcdn.com/w320/ir.png",
        languages: ["Persian (Farsi)"],
        continents: ["Asia"],
    },
    "Iceland":{
        capital: "Reykjavik",
        officialName: "Iceland",
        population: "391810",
        area: "103000",
        flag: "https://flagcdn.com/w320/is.png",
        languages: ["Icelandic"],
        continents: ["Europe"],
    },
    "Guinea":{
        capital: "Conakry",
        officialName: "Republic of Guinea",
        population: "14363931",
        area: "245857",
        flag: "https://flagcdn.com/w320/gn.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Svalbard and Jan Mayen":{
        capital: "Longyearbyen",
        officialName: "Svalbard og Jan Mayen",
        population: "2530",
        area: "61399",
        flag: "https://flagcdn.com/w320/sj.png",
        languages: ["Norwegian"],
        continents: ["Europe"],
    },
    "Kuwait":{
        capital: "Kuwait City",
        officialName: "State of Kuwait",
        population: "4881254",
        area: "17818",
        flag: "https://flagcdn.com/w320/kw.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "Morocco":{
        capital: "Rabat",
        officialName: "Kingdom of Morocco",
        population: "36828330",
        area: "446550",
        flag: "https://flagcdn.com/w320/ma.png",
        languages: ["Arabic","Berber"],
        continents: ["Africa"],
    },
    "Namibia":{
        capital: "Windhoek",
        officialName: "Republic of Namibia",
        population: "3022401",
        area: "825615",
        flag: "https://flagcdn.com/w320/na.png",
        languages: ["Afrikaans","German","English","Herero","Khoekhoe","Kwangali","Lozi","Ndonga","Tswana"],
        continents: ["Africa"],
    },
    "Tajikistan":{
        capital: "Dushanbe",
        officialName: "Republic of Tajikistan",
        population: "10499000",
        area: "143100",
        flag: "https://flagcdn.com/w320/tj.png",
        languages: ["Russian","Tajik"],
        continents: ["Asia"],
    },
    "Vanuatu":{
        capital: "Port Vila",
        officialName: "Republic of Vanuatu",
        population: "321409",
        area: "12189",
        flag: "https://flagcdn.com/w320/vu.png",
        languages: ["Bislama","English","French"],
        continents: ["Oceania"],
    },
    "Jamaica":{
        capital: "Kingston",
        officialName: "Jamaica",
        population: "2825544",
        area: "10991",
        flag: "https://flagcdn.com/w320/jm.png",
        languages: ["English","Jamaican Patois"],
        continents: ["North America"],
    },
    "Palau":{
        capital: "Ngerulmud",
        officialName: "Republic of Palau",
        population: "16733",
        area: "459",
        flag: "https://flagcdn.com/w320/pw.png",
        languages: ["English","Palauan"],
        continents: ["Oceania"],
    },
    "Uruguay":{
        capital: "Montevideo",
        officialName: "Oriental Republic of Uruguay",
        population: "3499451",
        area: "181034",
        flag: "https://flagcdn.com/w320/uy.png",
        languages: ["Spanish"],
        continents: ["South America"],
    },
    "Bhutan":{
        capital: "Thimphu",
        officialName: "Kingdom of Bhutan",
        population: "784043",
        area: "38394",
        flag: "https://flagcdn.com/w320/bt.png",
        languages: ["Dzongkha"],
        continents: ["Asia"],
    },
    "DR Congo":{
        capital: "Kinshasa",
        officialName: "Democratic Republic of the Congo",
        population: "112832000",
        area: "2344858",
        flag: "https://flagcdn.com/w320/cd.png",
        languages: ["French","Kikongo","Lingala","Tshiluba","Swahili"],
        continents: ["Africa"],
    },
    "Kazakhstan":{
        capital: "Astana",
        officialName: "Republic of Kazakhstan",
        population: "20426568",
        area: "2724900",
        flag: "https://flagcdn.com/w320/kz.png",
        languages: ["Kazakh","Russian"],
        continents: ["Asia"],
    },
    "Eritrea":{
        capital: "Asmara",
        officialName: "State of Eritrea",
        population: "3607000",
        area: "117600",
        flag: "https://flagcdn.com/w320/er.png",
        languages: ["Arabic","English","Tigrinya"],
        continents: ["Africa"],
    },
    "Gibraltar":{
        capital: "Gibraltar",
        officialName: "Gibraltar",
        population: "38000",
        area: "6",
        flag: "https://flagcdn.com/w320/gi.png",
        languages: ["English"],
        continents: ["Europe"],
    },
    "Gabon":{
        capital: "Libreville",
        officialName: "Gabonese Republic",
        population: "2469296",
        area: "267668",
        flag: "https://flagcdn.com/w320/ga.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Peru":{
        capital: "Lima",
        officialName: "Republic of Peru",
        population: "34350244",
        area: "1285216",
        flag: "https://flagcdn.com/w320/pe.png",
        languages: ["Aymara","Quechua","Spanish"],
        continents: ["South America"],
    },
    "Denmark":{
        capital: "Copenhagen",
        officialName: "Kingdom of Denmark",
        population: "6011488",
        area: "43094",
        flag: "https://flagcdn.com/w320/dk.png",
        languages: ["Danish"],
        continents: ["Europe"],
    },
    "Croatia":{
        capital: "Zagreb",
        officialName: "Republic of Croatia",
        population: "3866233",
        area: "56594",
        flag: "https://flagcdn.com/w320/hr.png",
        languages: ["Croatian"],
        continents: ["Europe"],
    },
    "Curaçao":{
        capital: "Willemstad",
        officialName: "Country of Curaçao",
        population: "156115",
        area: "444",
        flag: "https://flagcdn.com/w320/cw.png",
        languages: ["English","Dutch","Papiamento"],
        continents: ["North America"],
    },
    "British Indian Ocean Territory":{
        capital: "Diego Garcia",
        officialName: "British Indian Ocean Territory",
        population: "0",
        area: "60",
        flag: "https://flagcdn.com/w320/io.png",
        languages: ["English"],
        continents: ["Asia"],
    },
    "Norway":{
        capital: "Oslo",
        officialName: "Kingdom of Norway",
        population: "5606944",
        area: "386224",
        flag: "https://flagcdn.com/w320/no.png",
        languages: ["Norwegian Nynorsk","Norwegian Bokmål","Sami"],
        continents: ["Europe"],
    },
    "Lesotho":{
        capital: "Maseru",
        officialName: "Kingdom of Lesotho",
        population: "2116427",
        area: "30355",
        flag: "https://flagcdn.com/w320/ls.png",
        languages: ["English","Sotho"],
        continents: ["Africa"],
    },
    "Austria":{
        capital: "Vienna",
        officialName: "Republic of Austria",
        population: "9200931",
        area: "83871",
        flag: "https://flagcdn.com/w320/at.png",
        languages: ["German"],
        continents: ["Europe"],
    },
    "Switzerland":{
        capital: "Bern",
        officialName: "Swiss Confederation",
        population: "9082848",
        area: "41284",
        flag: "https://flagcdn.com/w320/ch.png",
        languages: ["French","Swiss German","Italian","Romansh"],
        continents: ["Europe"],
    },
    "Belize":{
        capital: "Belmopan",
        officialName: "Belize",
        population: "417634",
        area: "22966",
        flag: "https://flagcdn.com/w320/bz.png",
        languages: ["Belizean Creole","English","Spanish"],
        continents: ["North America"],
    },
    "Belgium":{
        capital: "Brussels",
        officialName: "Kingdom of Belgium",
        population: "11825551",
        area: "30528",
        flag: "https://flagcdn.com/w320/be.png",
        languages: ["German","French","Dutch"],
        continents: ["Europe"],
    },
    "Nicaragua":{
        capital: "Managua",
        officialName: "Republic of Nicaragua",
        population: "6803886",
        area: "130373",
        flag: "https://flagcdn.com/w320/ni.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "United States Virgin Islands":{
        capital: "Charlotte Amalie",
        officialName: "Virgin Islands of the United States",
        population: "87146",
        area: "347",
        flag: "https://flagcdn.com/w320/vi.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Singapore":{
        capital: "Singapore",
        officialName: "Republic of Singapore",
        population: "6110200",
        area: "710",
        flag: "https://flagcdn.com/w320/sg.png",
        languages: ["English","Chinese","Malay","Tamil"],
        continents: ["Asia"],
    },
    "Dominican Republic":{
        capital: "Santo Domingo",
        officialName: "Dominican Republic",
        population: "10771504",
        area: "48671",
        flag: "https://flagcdn.com/w320/do.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Kosovo":{
        capital: "Pristina",
        officialName: "Republic of Kosovo",
        population: "1585566",
        area: "10908",
        flag: "https://flagcdn.com/w320/xk.png",
        languages: ["Albanian","Serbian"],
        continents: ["Europe"],
    },
    "Laos":{
        capital: "Vientiane",
        officialName: "Lao People's Democratic Republic",
        population: "7647000",
        area: "236800",
        flag: "https://flagcdn.com/w320/la.png",
        languages: ["Lao"],
        continents: ["Asia"],
    },
    "Chile":{
        capital: "Santiago",
        officialName: "Republic of Chile",
        population: "20206953",
        area: "756102",
        flag: "https://flagcdn.com/w320/cl.png",
        languages: ["Spanish"],
        continents: ["South America"],
    },
    "Costa Rica":{
        capital: "San José",
        officialName: "Republic of Costa Rica",
        population: "5309625",
        area: "51100",
        flag: "https://flagcdn.com/w320/cr.png",
        languages: ["Spanish"],
        continents: ["North America"],
    },
    "Rwanda":{
        capital: "Kigali",
        officialName: "Republic of Rwanda",
        population: "14104969",
        area: "26338",
        flag: "https://flagcdn.com/w320/rw.png",
        languages: ["English","French","Kinyarwanda"],
        continents: ["Africa"],
    },
    "Trinidad and Tobago":{
        capital: "Port of Spain",
        officialName: "Republic of Trinidad and Tobago",
        population: "1367764",
        area: "5130",
        flag: "https://flagcdn.com/w320/tt.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Malaysia":{
        capital: "Kuala Lumpur",
        officialName: "Malaysia",
        population: "34231700",
        area: "330803",
        flag: "https://flagcdn.com/w320/my.png",
        languages: ["English","Malay"],
        continents: ["Asia"],
    },
    "South Africa":{
        capital: "Pretoria",
        officialName: "Republic of South Africa",
        population: "63100945",
        area: "1221037",
        flag: "https://flagcdn.com/w320/za.png",
        languages: ["Afrikaans","English","Southern Ndebele","Northern Sotho","Southern Sotho","Swazi","Tswana","Tsonga","Venda","Xhosa","Zulu"],
        continents: ["Africa"],
    },
    "Saudi Arabia":{
        capital: "Riyadh",
        officialName: "Kingdom of Saudi Arabia",
        population: "35300280",
        area: "2149690",
        flag: "https://flagcdn.com/w320/sa.png",
        languages: ["Arabic"],
        continents: ["Asia"],
    },
    "Haiti":{
        capital: "Port-au-Prince",
        officialName: "Republic of Haiti",
        population: "11867032",
        area: "27750",
        flag: "https://flagcdn.com/w320/ht.png",
        languages: ["French","Haitian Creole"],
        continents: ["North America"],
    },
    "French Southern and Antarctic Lands":{
        capital: "Port-aux-Français",
        officialName: "Territory of the French Southern and Antarctic Lands",
        population: "400",
        area: "7747",
        flag: "https://flagcdn.com/w320/tf.png",
        languages: ["French"],
        continents: ["Antarctica"],
    },
    "Tokelau":{
        capital: "Fakaofo",
        officialName: "Tokelau",
        population: "2608",
        area: "12",
        flag: "https://flagcdn.com/w320/tk.png",
        languages: ["English","Samoan","Tokelauan"],
        continents: ["Oceania"],
    },
    "Somalia":{
        capital: "Mogadishu",
        officialName: "Federal Republic of Somalia",
        population: "19655000",
        area: "637657",
        flag: "https://flagcdn.com/w320/so.png",
        languages: ["Arabic","Somali"],
        continents: ["Africa"],
    },
    "Japan":{
        capital: "Tokyo",
        officialName: "Japan",
        population: "123210000",
        area: "377930",
        flag: "https://flagcdn.com/w320/jp.png",
        languages: ["Japanese"],
        continents: ["Asia"],
    },
    "Macau":{
        capital: "",
        officialName: "Macao Special Administrative Region of the People's Republic of China",
        population: "685900",
        area: "30",
        flag: "https://flagcdn.com/w320/mo.png",
        languages: ["Portuguese","Chinese"],
        continents: ["Asia"],
    },
    "Sudan":{
        capital: "Khartoum",
        officialName: "Republic of the Sudan",
        population: "51662000",
        area: "1886068",
        flag: "https://flagcdn.com/w320/sd.png",
        languages: ["Arabic","English"],
        continents: ["Africa"],
    },
    "Algeria":{
        capital: "Algiers",
        officialName: "People's Democratic Republic of Algeria",
        population: "47400000",
        area: "2381741",
        flag: "https://flagcdn.com/w320/dz.png",
        languages: ["Arabic"],
        continents: ["Africa"],
    },
    "Eswatini":{
        capital: "Mbabane",
        officialName: "Kingdom of Eswatini",
        population: "1235549",
        area: "17364",
        flag: "https://flagcdn.com/w320/sz.png",
        languages: ["English","Swazi"],
        continents: ["Africa"],
    },
    "France":{
        capital: "Paris",
        officialName: "French Republic",
        population: "66351959",
        area: "543908",
        flag: "https://flagcdn.com/w320/fr.png",
        languages: ["French"],
        continents: ["Europe"],
    },
    "Sint Maarten":{
        capital: "Philipsburg",
        officialName: "Sint Maarten",
        population: "41349",
        area: "34",
        flag: "https://flagcdn.com/w320/sx.png",
        languages: ["English","French","Dutch"],
        continents: ["North America"],
    },
    "Bangladesh":{
        capital: "Dhaka",
        officialName: "People's Republic of Bangladesh",
        population: "169828911",
        area: "147570",
        flag: "https://flagcdn.com/w320/bd.png",
        languages: ["Bengali"],
        continents: ["Asia"],
    },
    "Central African Republic":{
        capital: "Bangui",
        officialName: "Central African Republic",
        population: "6470307",
        area: "622984",
        flag: "https://flagcdn.com/w320/cf.png",
        languages: ["French","Sango"],
        continents: ["Africa"],
    },
    "Canada":{
        capital: "Ottawa",
        officialName: "Canada",
        population: "41651653",
        area: "9984670",
        flag: "https://flagcdn.com/w320/ca.png",
        languages: ["English","French"],
        continents: ["North America"],
    },
    "Réunion":{
        capital: "Saint-Denis",
        officialName: "Réunion Island",
        population: "896175",
        area: "2511",
        flag: "https://flagcdn.com/w320/re.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Saint Vincent and the Grenadines":{
        capital: "Kingstown",
        officialName: "Saint Vincent and the Grenadines",
        population: "110872",
        area: "389",
        flag: "https://flagcdn.com/w320/vc.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Micronesia":{
        capital: "Palikir",
        officialName: "Federated States of Micronesia",
        population: "105564",
        area: "702",
        flag: "https://flagcdn.com/w320/fm.png",
        languages: ["English"],
        continents: ["Oceania"],
    },
    "Cape Verde":{
        capital: "Praia",
        officialName: "Republic of Cabo Verde",
        population: "491233",
        area: "4033",
        flag: "https://flagcdn.com/w320/cv.png",
        languages: ["Portuguese"],
        continents: ["Africa"],
    },
    "Grenada":{
        capital: "St. George's",
        officialName: "Grenada",
        population: "109021",
        area: "344",
        flag: "https://flagcdn.com/w320/gd.png",
        languages: ["English"],
        continents: ["North America"],
    },
    "Pakistan":{
        capital: "Islamabad",
        officialName: "Islamic Republic of Pakistan",
        population: "241499431",
        area: "796095",
        flag: "https://flagcdn.com/w320/pk.png",
        languages: ["English","Urdu"],
        continents: ["Asia"],
    },
    "Nepal":{
        capital: "Kathmandu",
        officialName: "Federal Democratic Republic of Nepal",
        population: "29911840",
        area: "147181",
        flag: "https://flagcdn.com/w320/np.png",
        languages: ["Nepali"],
        continents: ["Asia"],
    },
    "Bosnia and Herzegovina":{
        capital: "Sarajevo",
        officialName: "Bosnia and Herzegovina",
        population: "3422000",
        area: "51209",
        flag: "https://flagcdn.com/w320/ba.png",
        languages: ["Bosnian","Croatian","Serbian"],
        continents: ["Europe"],
    },
    "South Sudan":{
        capital: "Juba",
        officialName: "Republic of South Sudan",
        population: "15786898",
        area: "619745",
        flag: "https://flagcdn.com/w320/ss.png",
        languages: ["English"],
        continents: ["Africa"],
    },
    "Guinea-Bissau":{
        capital: "Bissau",
        officialName: "Republic of Guinea-Bissau",
        population: "1781308",
        area: "36125",
        flag: "https://flagcdn.com/w320/gw.png",
        languages: ["Portuguese","Upper Guinea Creole"],
        continents: ["Africa"],
    },
    "Benin":{
        capital: "Porto-Novo",
        officialName: "Republic of Benin",
        population: "13224860",
        area: "112622",
        flag: "https://flagcdn.com/w320/bj.png",
        languages: ["French"],
        continents: ["Africa"],
    },
    "Lebanon":{
        capital: "Beirut",
        officialName: "Lebanese Republic",
        population: "5490000",
        area: "10452",
        flag: "https://flagcdn.com/w320/lb.png",
        languages: ["Arabic","French"],
        continents: ["Asia"],
    },
    "Åland Islands":{
        capital: "Mariehamn",
        officialName: "Åland Islands",
        population: "30654",
        area: "1580",
        flag: "https://flagcdn.com/w320/ax.png",
        languages: ["Swedish"],
        continents: ["Europe"],
    }
}


export default countries;

